[package]
name = "multer"
version = "1.2.2"
description = "An async parser for `multipart/form-data` content-type in Rust."
homepage = "https://github.com/rousan/multer-rs"
repository = "https://github.com/rousan/multer-rs"
keywords = ["multipart-formdata", "multipart-uploads", "async", "formdata"]
categories = ["asynchronous", "web-programming"]
authors = ["Rousan Ali <hello@rousan.io>"]
readme = "README.md"
license = "MIT"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
features = ["all"]

[features]
default = []
all = ["json"]
json = ["serde", "serde_json"]
tokio-io = ["tokio", "tokio-util"]

[dependencies]
log = "0.4"
bytes = "0.5"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
futures_codec = "0.4.1"
twoway = "0.2"
http = "0.2"
httparse = "1.3"
mime = "0.3"
regex = "1.3"
once_cell = "1.4"
encoding_rs = "0.8"
derive_more = "0.99"

serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
tokio = { version = "0.2", optional = true }
tokio-util = { version = "0.3.1", features = ["codec"],  optional = true }

[dev-dependencies]
futures = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
hyper = "0.13"
routerify = "1.1"
